import { APITestConfig } from "./type";

const viewerTestConfigs: APITestConfig[] = [
  { path: "reearth.viewer.property" },
  { path: "reearth.viewer.overrideProperty" },
  { path: "reearth.viewer.viewport" },
  { path: "reearth.viewer.capture" },
  { path: "reearth.viewer.interactionMode.mode" },
  { path: "reearth.viewer.interactionMode.override" },
  { path: "reearth.viewer.interactionMode.selectionMode.on.marqueeStart" },
  { path: "reearth.viewer.interactionMode.selectionMode.on.marqueeMove" },
  { path: "reearth.viewer.interactionMode.selectionMode.on.marqueeEnd" },
  {
    path: "reearth.viewer.interactionMode.selectionMode.off.marqueeStart",
  },
  {
    path: "reearth.viewer.interactionMode.selectionMode.off.marqueeMove",
  },
  {
    path: "reearth.viewer.interactionMode.selectionMode.off.marqueeEnd",
  },
  { path: "reearth.viewer.env.inEditor" },
  { path: "reearth.viewer.env.isBuilt" },
  { path: "reearth.viewer.tools.getLocationFromScreenCoordinate" },
  { path: "reearth.viewer.tools.getScreenCoordinateFromPosition" },
  { path: "reearth.viewer.tools.getTerrainHeightAsync" },
  { path: "reearth.viewer.tools.getGlobeHeight" },
  { path: "reearth.viewer.tools.getGlobeHeightByCamera" },
  { path: "reearth.viewer.tools.cartographicToCartesian" },
  { path: "reearth.viewer.tools.cartesianToCartographic" },
  { path: "reearth.viewer.tools.transformByOffsetOnScreen" },
  { path: "reearth.viewer.tools.isPositionVisibleOnGlobe" },
  { path: "reearth.viewer.on.click" },
  { path: "reearth.viewer.on.doubleClick" },
  { path: "reearth.viewer.on.mouseDown" },
  { path: "reearth.viewer.on.mouseUp" },
  { path: "reearth.viewer.on.rightClick" },
  { path: "reearth.viewer.on.rightDown" },
  { path: "reearth.viewer.on.rightUp" },
  { path: "reearth.viewer.on.middleClick" },
  { path: "reearth.viewer.on.middleDown" },
  { path: "reearth.viewer.on.middleUp" },
  { path: "reearth.viewer.on.mouseMove" },
  { path: "reearth.viewer.on.mouseEnter" },
  { path: "reearth.viewer.on.mouseLeave" },
  { path: "reearth.viewer.on.wheel" },
  { path: "reearth.viewer.on.resize" },
  { path: "reearth.viewer.off.click" },
  { path: "reearth.viewer.off.doubleClick" },
  { path: "reearth.viewer.off.mouseDown" },
  { path: "reearth.viewer.off.mouseUp" },
  { path: "reearth.viewer.off.rightClick" },
  { path: "reearth.viewer.off.rightDown" },
  { path: "reearth.viewer.off.rightUp" },
  { path: "reearth.viewer.off.middleClick" },
  { path: "reearth.viewer.off.middleDown" },
  { path: "reearth.viewer.off.middleUp" },
  { path: "reearth.viewer.off.mouseMove" },
  { path: "reearth.viewer.off.mouseEnter" },
  { path: "reearth.viewer.off.mouseLeave" },
  { path: "reearth.viewer.off.wheel" },
  { path: "reearth.viewer.off.resize" },
];

export default viewerTestConfigs;
